
sudo: required

services:
    - docker

language: c
compiler:
    - gcc

before_install:
    - sudo apt-get -qy update
    # wireshark.pc location: http://packages.ubuntu.com/tr/trusty/amd64/libwireshark-dev/filelist
    #somehow doesn't work: - export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}"

install: 
    - sudo apt-get -qy install libwireshark-dev wireshark-dev
    - wget https://www.wireshark.org/download/src/wireshark-2.0.2.tar.bz2
    - tar xf wireshark-2.0.2.tar.bz2
    - mv wireshark-2.0.2 wireshark
    - cp -R ./src/plugins/doip ./wireshark/plugins/doip/ 
    - cp -R ./src/plugins/Custom.* ./wireshark/plugins/
    - cd ./wireshark && bash ./autogen.sh && cd ~-
    - cd ./wireshark && ./configure --enable-wireshark=no && cd ~-

script: 
    - ls ./wireshark/plugins/
    - cat ./wireshark/plugins/Makefile.am
    - ls ./wireshark/plugins/doip
    - make -C ./wireshark/plugins/doip
    
   # Build a docker image
    - docker/build
     # Login to dockerhub and push the image built into the dockerhub
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker pull hannesd/amos-downloader-image:1.0
    - docker build -t jufuch/amos-ss16-proj3 docker/
    #push the image built 
    - docker push jufuch/amos-ss16-proj3



